using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.Json.Serialization;
using System.Threading.Tasks;

// Surpress for now, since this class was mostly autogenerated from existing json data
#pragma warning disable CS8618 // Non-nullable field must contain a non-null value when exiting constructor. Consider adding the 'required' modifier or declaring as nullable.
namespace Todoist2SuperProductivity.Data
{
	// Messy class to represent Todoist sync data
	// Should contain all *active* data from todoist
	// TODO for completed items https://developer.todoist.com/sync/v9/#get-all-completed-items
	internal class SyncData
	{
		[JsonPropertyName("items")]
		public List<Task> Tasks { get; set; } = [];
		[JsonPropertyName("labels")]
		public List<Label> Labels { get; set; } = [];
		[JsonPropertyName("notes")]
		public List<Note> Comments { get; set; } = [];
		[JsonPropertyName("projects")]
		public List<Project> Projects { get; set; } = [];
		[JsonPropertyName("reminders")]
		public List<Reminder> Reminders { get; set; } = [];
		[JsonPropertyName("sections")]
		public List<Section> Sections { get; set; } = [];

		public class Section
		{
			public DateTime added_at { get; set; }
			public object archived_at { get; set; }
			public bool collapsed { get; set; }
			public string id { get; set; }
			public bool is_archived { get; set; }
			public bool is_deleted { get; set; }
			public string name { get; set; }
			public string project_id { get; set; }
			public int section_order { get; set; }
			public object sync_id { get; set; }
			public DateTime updated_at { get; set; }
			public string user_id { get; set; }
			public string v2_id { get; set; }
			public string v2_project_id { get; set; }
		}

		public class Reminder
		{
			public Due due { get; set; }
			public string id { get; set; }
			public bool is_deleted { get; set; }
			public string item_id { get; set; }
			public int minute_offset { get; set; }
			public string notify_uid { get; set; }
			public string type { get; set; }
			public string v2_id { get; set; }
			public string v2_item_id { get; set; }
		}

		public class Project
		{
			public bool can_assign_tasks { get; set; }
			public int child_order { get; set; }
			public bool collapsed { get; set; }
			public string color { get; set; }
			public DateTime created_at { get; set; }
			public string id { get; set; }
			public bool inbox_project { get; set; }
			public bool is_archived { get; set; }
			public bool is_deleted { get; set; }
			public bool is_favorite { get; set; }
			public bool is_frozen { get; set; }
			public string name { get; set; }
			public object parent_id { get; set; }
			public bool shared { get; set; }
			public object sync_id { get; set; }
			public DateTime updated_at { get; set; }
			public string v2_id { get; set; }
			public object v2_parent_id { get; set; }
			public string view_style { get; set; }
		}

		public class Note
		{
			public string content { get; set; }
			public object file_attachment { get; set; }
			public string id { get; set; }
			public bool is_deleted { get; set; }
			public string item_id { get; set; }
			public DateTime posted_at { get; set; }
			public string posted_uid { get; set; }
			public object reactions { get; set; }
			public string[] uids_to_notify { get; set; }
			public string v2_id { get; set; }
			public string v2_item_id { get; set; }
		}

		public class Label
		{
			public string color { get; set; }
			public string id { get; set; }
			public bool is_deleted { get; set; }
			public bool is_favorite { get; set; }
			public int item_order { get; set; }
			public string name { get; set; }
		}


		public class Task
		{
			public DateTime added_at { get; set; }
			public string added_by_uid { get; set; }
			public object assigned_by_uid { get; set; }
			public bool _checked { get; set; }
			public int child_order { get; set; }
			public bool collapsed { get; set; }
			public object completed_at { get; set; }
			public string content { get; set; }
			public int day_order { get; set; }
			public object deadline { get; set; }
			public string description { get; set; }
			public Due due { get; set; }
			public object duration { get; set; }
			public string id { get; set; }
			public bool is_deleted { get; set; }
			public string[] labels { get; set; }
			public object parent_id { get; set; }
			public int priority { get; set; }
			public string project_id { get; set; }
			public object responsible_uid { get; set; }
			public object section_id { get; set; }
			public object sync_id { get; set; }
			public DateTime updated_at { get; set; }
			public string user_id { get; set; }
			public string v2_id { get; set; }
			public object v2_parent_id { get; set; }
			public string v2_project_id { get; set; }
			public object v2_section_id { get; set; }
		}

		public class Due
		{
			public string date { get; set; }
			public bool is_recurring { get; set; }
			public string lang { get; set; }
			public string _string { get; set; }
			public object timezone { get; set; }
		}
	}
}
